import emanuele from "./Images/emauele.jpg";
// import liane from "./Images/liane.jpg";
// import wellington from "./Images/wellington.jpg";
// import alceni from "./Images/alceni.jpg";
// import batista from "./Images/batista.jpg";
// import luciano from "./Images/luciano.jpg";
// import chico from "./Images/chico.jpg";

export const Filiados = [
  {
    cidade: [
      {
        nome: "Novo Hamburgo",
        equipes: [
          {
            id: 1,
            equipe: "Kim Yu Shin",
            alvara_valido: true,
            responsavel: "Francisco Chagas da Luz",
            cidade: "Novo Hamburgo",
            endereco: "Rua Bartolomeu de Gusmão 1411",
            contato: "51 9 9999-999",
            alunos_filiados: [
              {
                id: 1,
                nome: "Emanuele Mariane Padilha da Luz",
                graduacao: "2° Dan",
                data_nascimento: "26/12/2009",
                n_lgam: 123456,
                n_liga_nacional: 123456,
                foto: emanuele,
              },
              {
                id: 2,
                nome: "Jeferson Josué Padilha Soares",
                graduacao: "2° Dan",
                data_nascimento: "15/06/1999",
                n_lgam: 123456,
                n_liga_nacional: 123456,
                foto: emanuele,
              },
            ],
          },
        ],
      },
      {
        nome: "São Leopoldo",
        equipes: [
          {
            id: 1,
            equipe: "Kim Yu Shin 2",
            alvara_valido: true,
            responsavel: "Francisco Chagas da Luz",
            cidade: "Novo Hamburgo",
            endereco: "Rua Bartolomeu de Gusmão 1411",
            contato: "51 9 9999-999",
            alunos_filiados: [
              {
                id: 1,
                nome: "Emanuele Mariane Padilha da Luz",
                graduacao: "2° Dan",
                data_nascimento: "26/12/2009",
                n_lgam: 123456,
                n_liga_nacional: 123456,
                foto: emanuele,
              },
              {
                id: 2,
                nome: "Jeferson Josué Padilha Soares",
                graduacao: "2° Dan",
                data_nascimento: "15/06/1999",
                n_lgam: 123456,
                n_liga_nacional: 123456,
                foto: emanuele,
              },
            ],
          },
        ],
      },
    ],
  },

  // {
  //   id: 1,
  //   nome: "Emanuele Mariane Padilha da Luz",
  //   academia: "Kim Yu Shin",
  //   faixa: "Preta 1º Dan",
  //   nascimento: "27/12/2009",
  //   localidade: "Novo Hamburgo / RS",
  //   mestre: "Francisco Chagas da Luz",
  //   registroLGAM: "0034/2024",
  //   registroLN: "",
  //   foto: emanuele,
  // },
  // {
  //   id: 2,
  //   nome: "Eliane de Avila Padilha",
  //   academia: "Kim Yu Shin",
  //   faixa: "Preta 4º Dan",
  //   nascimento: "16/05/1982",
  //   localidade: "Novo Hamburgo / RS",
  //   mestre: "Francisco Chagas da Luz",
  //   registroLGAM: "0002/2024",
  //   registroLN: "",
  //   foto: liane,
  // },
  // {
  //   id: 3,
  //   nome: "Francisco Chagas da Luz",
  //   academia: "Kim Yu Shin",
  //   faixa: "Preta 5º Dan",
  //   nascimento: "22/12/1969",
  //   localidade: "Novo Hamburgo / RS",
  //   mestre: "",
  //   registroLGAM: "0001/2024",
  //   registroLN: "3439",
  //   foto: chico,
  // },
  // {
  //   id: 4,
  //   nome: "Wellington Bernardes",
  //   academia: "Kim Yu Shin",
  //   faixa: "Faixa Preta 1º DAN",
  //   nascimento: "03/02/2003",
  //   localidade: "Parobé / RS",
  //   mestre: "Francisco Chagas da Luz",
  //   registroLGAM: "0030/2024",
  //   registroLN: "4080",
  //   foto: wellington,
  // },
  // {
  //   id: 5,
  //   nome: "Carlos Antonio Batista",
  //   academia: "Kim Yu Shin",
  //   faixa: "Faixa Colorida",
  //   nascimento: "30/07/1973",
  //   localidade: "Novo Hamburgo / RS",
  //   mestre: "Francisco Chagas da Luz",
  //   registroLGAM: "0031/2024",
  //   registroLN: "",
  //   foto: batista,
  // },
  // {
  //   id: 6,
  //   nome: "João Viktor Garcia da Veiga",
  //   academia: "Kim Yu Shin",
  //   faixa: "Faixa Colorida",
  //   nascimento: "03/10/2008",
  //   localidade: "Novo Hamburgo / RS",
  //   mestre: "Francisco Chagas da Luz",
  //   registroLGAM: "0032/2024",
  //   registroLN: "",
  //   foto: "",
  // },
  // {
  //   id: 7,
  //   nome: "Alceni da Silva",
  //   academia: "Kim Yu Shin",
  //   faixa: "Faixa Preta 2º DAN",
  //   nascimento: "22/10/1975",
  //   localidade: "Parobé / RS",
  //   mestre: "Francisco Chagas da Luz",
  //   registroLGAM: "0033/2024",
  //   registroLN: "",
  //   foto: alceni,
  // },
  // {
  //   id: 8,
  //   nome: "Luciano da Silva",
  //   academia: "Dragon",
  //   faixa: "Faixa Preta 2º DAN",
  //   nascimento: "07/11/1975",
  //   localidade: "Montenegro / RS",
  //   mestre: "Francisco Chagas da Luz",
  //   registroLGAM: "",
  //   registroLN: "3704",
  //   foto: luciano,
  // },
  // {
  //   id: 9,
  //   nome: "Eduardo Flores",
  //   academia: "THE FLASH",
  //   faixa: "Faixa Preta 2º DAN",
  //   nascimento: "13/11/1980",
  //   localidade: "São Leopoldo / RS",
  //   mestre: "Francisco Chagas da Luz",
  //   registroLGAM: "",
  //   registroLN: "0363",
  //   foto: "",
  // },
  // {
  //   id: 10,
  //   nome: "André Felippe",
  //   academia: "MID NIGHT TEAM",
  //   faixa: "Faixa Preta 1º DAN",
  //   nascimento: "15/05/1996",
  //   localidade: "Sobradinho / RS",
  //   mestre: "Francisco Chagas da Luz",
  //   registroLGAM: "",
  //   registroLN: "4048",
  //   foto: "",
  // },
  // {
  //   nome: "Alex Diniz Lopes",
  //   academia: "Kim Yu Shin",
  //   faixa: "Faixa Preta 1º DAN",
  //   nascimento: "16/01/2001",
  //   localidade: "Novo Hamburgo / RS",
  //   mestre: "Francisco Chagas da Luz",
  //   registroLGAM: "",
  //   registroLN: "935",
  //   foto: "",
  // },
];

export const Cidades = {
  cidade: [
    {
      nome: "Novo Hamburgo",
      equipes: [
        {
          id: 1,
          nome_equipe: "Kim Yu Shin",
          alvara_valido: true,
          responsavel: "Francisco Chagas da Luz",
          endereco: "Rua Bartolomeu de Gusmão 1411",
          contato: "51 9 9999-999",
          alunos_filiados: [
            {
              id: 1,
              nome_aluno: "Emanuele Mariane Padilha da Luz",
              graduacao: "2° Dan",
              data_nascimento: "26/12/2009",
              n_lgam: 123456,
              n_liga_nacional: 123456,
              foto: emanuele,
            },
            {
              id: 2,
              nome_aluno: "Jeferson Josué Padilha Soares",
              graduacao: "2° Dan",
              data_nascimento: "15/06/1999",
              n_lgam: 123456,
              n_liga_nacional: 123456,
              foto: emanuele,
            },
          ],
        },
      ],
    },
    {
      nome: "São Leopoldo",
      equipes: [
        {
          id: 1,
          nome_equipe: "Kim Yu Shin 2",
          alvara_valido: true,
          responsavel: "Francisco Chagas da Luz",
          endereco: "Rua Bartolomeu de Gusmão 1411",
          contato: "51 9 9999-999",
          alunos_filiados: [
            {
              id: 1,
              nome_aluno: "Emanuele Mariane Padilha da Luz",
              graduacao: "2° Dan",
              data_nascimento: "26/12/2009",
              n_lgam: 123456,
              n_liga_nacional: 123456,
              foto: emanuele,
            },
            {
              id: 2,
              nome_aluno: "Jeferson Josué Padilha Soares",
              graduacao: "2° Dan",
              data_nascimento: "15/06/1999",
              n_lgam: 123456,
              n_liga_nacional: 123456,
              foto: emanuele,
            },
          ],
        },
      ],
    },
  ],
};
