import emanuele from "./Images/emauele.jpg";
import liane from "./Images/liane.jpg";
import wellington from "./Images/wellington.jpg";
import alceni from "./Images/alceni.jpg";

export const Filiados = [
  {
    id: 1,
    nome: "Emanuele Mariane Padilha da Luz",
    academia: "Kim Yu Shin",
    faixa: "Preta 1º Dan",
    nascimento: "27/12/2009",
    localidade: "Novo Hamburgo",
    mestre: "Francisco Chagas da Luz",
    registroLGAM: null,
    registroLN: null,
    foto: emanuele,
  },
  {
    id: 2,
    nome: "Eliane de Avila Padilha",
    academia: "Kim Yu Shin",
    faixa: "Preta 4º Dan",
    nascimento: "16/05/1982",
    localidade: "Novo Hamburgo",
    mestre: "Francisco Chagas da Luz",
    registroLGAM: null,
    registroLN: null,
    foto: liane,
  },
  {
    id: 3,
    nome: "Fransico Chagas da Luz",
    academia: "Kim Yu Shin",
    faixa: "Preta 5º Dan",
    nascimento: "22/12/1969",
    localidade: "Novo Hamburgo",
    mestre: "",
    registroLGAM: null,
    registroLN: null,
    foto: "",
  },
  {
    id: 4,
    nome: "Wellington Bernardes",
    academia: "Kim Yu Shin",
    faixa: "Faixa Preta 1º DAN",
    nascimento: "03/02/2003",
    localidade: "Parobé",
    mestre: "Fransico Chagas da Luz",
    registroLGAM: null,
    registroLN: 4080,
    foto: wellington,
  },
  {
    id: 5,
    nome: "Carlos Antonio Batista",
    academia: "Kim Yu Shin",
    faixa: "Faixa Colorida",
    nascimento: "30/07/1973",
    localidade: "Novo Hamburgo",
    mestre: "Fransico Chagas da Luz",
    registroLGAM: null,
    registroLN: null,
    foto: "",
  },
  {
    id: 6,
    nome: "João Viktor Garcia da Veiga",
    academia: "Kim Yu Shin",
    faixa: "Faixa Colorida",
    nascimento: "03/10/2008",
    localidade: "Novo Hamburgo",
    mestre: "Fransico Chagas da Luz",
    registroLGAM: null,
    registroLN: null,
    foto: "",
  },
  {
    id: 7,
    nome: "Alceni da Silva",
    academia: "Kim Yu Shin",
    faixa: "Faixa Preta 2º DAN",
    nascimento: "22/10/1975",
    localidade: "Novo Hamburgo",
    mestre: "Fransico Chagas da Luz",
    registroLGAM: null,
    registroLN: null,
    foto: alceni,
  },
];
