import sapiranga from "../../assets/images/sapiranga.jpg";
import novoHamburgo from "../../assets/images/novoHamburgo.jpg";

import thumb_1 from "../../assets/images/Events/eventos_thumb_1.png";
import thumb_2 from "../../assets/images/Events/eventos_thumb_3.png";
import eventos_paulo from "../../assets/images/Events/eventos_paulo.jpg";

export const Events = [
  {
    id: 1,
    titulo: "1° Torneio Interno de Sapiranga",
    dia: "15",
    mes: "09",
    ano: "2024",
    local: "Rua Doutel de Andrade, 64 - Sapiranga",
    thumbnail: thumb_1,
    foto: sapiranga,
    inicio: "9 hrs",
    contato: [],
    infoAdd: [],
    organizacao: "LGAM",
    modalidades: ["Poom sae", "Sang Min Cho", "Kiorugui "],
  },
  {
    id: 2,
    titulo: "13° Open Kim Yu Shin",
    dia: "9 e 10",
    mes: "11",
    ano: "2024",
    local: "Ginásio Municipal de Novo Hamburgo",
    thumbnail: thumb_2,
    foto: novoHamburgo,
    inicio: "9 hrs",
    contato: ["51 9 8529-7929", "51 9 9546-7409"],
    infoAdd: [
      "Manhã do dia 9: Troca de faixa",
      "Tarde do dia 9: Poom sae",
      "Dia 10: Lutas",
    ],
    organizacao: "LGAM",
    modalidades: ["Poom sae", "Kiorugui "],
  },
  {
    id: 3,
    titulo: "Evento em homenagem ao Prof. Paulo Ferreira",
    dia: "23",
    mes: "02",
    ano: "2025",
    local: "",
    thumbnail: eventos_paulo,
    foto: eventos_paulo,
    inicio: "",
    contato: ["51 9 8529-7929", "51 9 9546-7409"],
    infoAdd: [
      "Evento em homenagem ao penta campeão paulo ferreira onde será também apresentação da seleção gaúcha LGAM",
      "Evento sujeito a mudança de data",
    ],
    organizacao: "",
    modalidades: [""],
  },
  {
    id: 4,
    titulo: "Torneio Interno",
    dia: "20",
    mes: "04",
    ano: "2025",
    local: "",
    thumbnail: "",
    foto: "",
    inicio: "",
    contato: ["51 9 8529-7929", "51 9 9546-7409"],
    infoAdd: ["Evento Interno"],
    organizacao: "LGAM",
    modalidades: [""],
  },

  {
    id: 5,
    titulo: "1º Seletiva",
    dia: "15",
    mes: "06",
    ano: "2025",
    local: "Novo Hamburgo",
    thumbnail: "",
    foto: "",
    inicio: "",
    contato: ["51 9 8529-7929", "51 9 9546-7409"],
    infoAdd: ["1º Seletiva"],
    organizacao: "LGAM",
    modalidades: [""],
  },

  {
    id: 5,
    titulo: "1º Seletiva",
    dia: "15",
    mes: "06",
    ano: "2025",
    local: "Novo Hamburgo",
    thumbnail: "",
    foto: "",
    inicio: "",
    contato: ["51 9 8529-7929", "51 9 9546-7409"],
    infoAdd: ["1º Seletiva"],
    organizacao: "LGAM",
    modalidades: [""],
  },
  {
    id: 5,
    titulo: "Troca de faixa preta e colorida",
    dia: "13",
    mes: "07",
    ano: "2025",
    local: "Novo Hamburgo",
    thumbnail: "",
    foto: "",
    inicio: "",
    contato: ["51 9 8529-7929", "51 9 9546-7409"],
    infoAdd: [""],
    organizacao: "LGAM",
    modalidades: [""],
  },
  {
    id: 6,
    titulo: "2º Seletiva - Torneio em Montenegro",
    dia: "10",
    mes: "08",
    ano: "2025",
    local: "Montenegro",
    thumbnail: "",
    foto: "",
    inicio: "",
    contato: ["51 9 8529-7929", "51 9 9546-7409"],
    infoAdd: [""],
    organizacao: "LGAM",
    modalidades: [""],
  },
  {
    id: 7,
    titulo: "3º Seletiva - Torneio Mestre Chico",
    dia: "27 e 28",
    mes: "08",
    ano: "2025",
    local: "Novo Hamburgo",
    thumbnail: "",
    foto: "",
    inicio: "",
    contato: ["51 9 8529-7929", "51 9 9546-7409"],
    infoAdd: ["Dia 27: Poom sae", "Dia 28: Kiorugui"],
    organizacao: "Kim Yu Shin",
    modalidades: ["Poom sae", "Kiorugui"],
  },
  {
    id: 8,
    titulo: "Copa América ",
    dia: "",
    mes: "10",
    ano: "2025",
    local: "",
    thumbnail: "",
    foto: "",
    inicio: "",
    contato: ["51 9 8529-7929", "51 9 9546-7409"],
    infoAdd: ["Dia 27: Poom sae", "Dia 28: Kiorugui"],
    organizacao: "LGAM",
    modalidades: ["Poom sae", "Kiorugui"],
  },
  {
    id: 9,
    titulo: "Troca de faixa preta e colorida em Novo Hamburgo",
    dia: "",
    mes: "10",
    ano: "2025",
    local: "Novo Hamburgo",
    thumbnail: "",
    foto: "",
    inicio: "",
    contato: ["51 9 8529-7929", "51 9 9546-7409"],
    infoAdd: ["Dia 27: Poom sae", "Dia 28: Kiorugui"],
    organizacao: "LGAM",
    modalidades: ["Poom sae", "Kiorugui"],
  },
  {
    id: 10,
    titulo: "Premiação dos melhores do ano",
    dia: "",
    mes: "10",
    ano: "2025",
    local: "Novo Hamburgo",
    thumbnail: "",
    foto: "",
    inicio: "",
    contato: ["51 9 8529-7929", "51 9 9546-7409"],
    infoAdd: [
      "Homenagens as academia com mais campeões",
      "Categoria colorida e pretas",
    ],
    organizacao: "LGAM",
    modalidades: ["Poom sae", "Kiorugui"],
  },
];
